server:
  port: 8079
logging:
  level:
    com:
      mpool: debug
spring:
  redis:
    host: redis-server
    port: 6379
    database: 0
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:
    - file:mpool-ui/
    - file:../../mpool-ui/
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
  mail:
    host: smtp.163.com
    port: 465
    username: wshstephen@163.com
    password: wsh4499345
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
  boot:
    admin:
      client:
        url:
        - http://checkup-server:2000
        instance:
          service-base-url: http://192.168.22.249:8080
        password: Admin@123
        username: admin
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
aliyun:
  sms:
    access-key-id: LTAITHtOEev5EtC0
    access-key-secret: CcFTGjbDyIft0HgcaHbyAT7Lj9KIiN
    sign-name: 蜂鸟
qq:
  captcha:
    aid: 2074816991
    verify-url: https://ssl.captcha.qq.com/ticket/verify
    app-secret-key: 0nPmvC_uzCkBEbRE3WERnwg**
sharding:
  jdbc:
    datasource:
      accountdb:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # rm-j6cyw99pjuui9l266.mysql.rds.aliyuncs.com
        jdbcUrl: jdbc:mysql://rm-j6cyw99pjuui9l2663o.mysql.rds.aliyuncs.com:3306/h_pool_account?characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: pool
        password: 3eZTsHL3KCK+lw==
      statsdb:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://rm-2ze22g9751h8u5k888o.mysql.rds.aliyuncs.com:3306/bpool_local_db?characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: pool_history
        password: 3@f35FR%Go-AZ!g!7swZc-8ryt
      workersdb:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://rm-2ze9nysk96o3o99m4lo.mysql.rds.aliyuncs.com:3306/bpool_local_db?characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: pool_realtime
        password: 1@f45FR%Go&AZDg!7swZc-8ryt
wx:
  miniapp:
    configs:
        - appid: wx94fa46b3614974b8
          secret: 42f3b7b27968fed18a832651045780ec
          token: #微信小程序消息服务器配置的token
          aesKey: #微信小程序消息服务器配置的EncodingAESKey
          msgDataFormat: JSON
