spring:
  redis:
    host: redis-server
    database: 0
    port: 6379
  boot:
    admin:
      client:
        url:
        - http://checkup-server:8080
      instance:
        service-base-url: http://loaclhost:8082
      password: Admin@123
      username: admin
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: noreply@hummerpool.com
    password: Hummer123
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true
logging:
  level:
    com.btc: debug
com:
  mpool:
    canal:
      destination: example
      region-id: 1
      serveraddress: canal-server
      subscribe: .*\\.mining_workers
      batch-size: 256
sharding:
  jdbc:
    datasource:
      btcaccountdb:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://rm-j6cyw99pjuui9l266.mysql.rds.aliyuncs.com:3306/h_pool_account?characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: pool
        password: 3eZTsHL3KCK+lw==
      ztcaccountdb:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://rm-j6cyw99pjuui9l266.mysql.rds.aliyuncs.com:3306/h_pool_zcrash?characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: pool
        password: 3eZTsHL3KCK+lw==