

server:
  port: 9898

service:
    name: 6

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 5
        max-idle: 2
        min-idle: 2
        max-wait: 10ms
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
#  redis2:
#    database: 0
#    host: 192.168.146.130
#    port: 6379
#    password: 123456
#    timeout: 3
#    lettuce:
#      pool:
#        max-active: 50
#        max-wait: 15
#        max-idle: 50
#        min-idle: 0

#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848