

server:
  port: 9898

spring:
  redis:
    database: 0
    host: 192.168.146.129
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 50
        max-wait: 15
        max-idle: 50
        min-idle: 0
  redis2:
    database: 0
    host: 192.168.146.130
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 50
        max-wait: 15
        max-idle: 50
        min-idle: 0

#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848