logging:
  level:
    com:
      mpool: debug
spring:
  redis:
    host: redis-server
    port: 6379
    database: 0
  mvc:
    static-path-pattern: /**
  resources:
    static-locations:
    - file:mpool-admin-ui/
    - file:../../mpool-admin-ui/
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
  mail:
      host: smtp.exmail.qq.com
      port: 465
      username: noreply@hummerpool.com
      password: Hummer123
      default-encoding: UTF-8
      properties:
        mail:
          smtp:
            socketFactory:
              class: javax.net.ssl.SSLSocketFactory
          debug: true
  boot:
    admin:
      client:
        url:
        - http://db-server:2000
        instance:
          service-base-url: http://192.168.22.249:8001
        password: Admin@123
        username: admin
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
aliyun:
  sms:
    access-key-id: LTAITHtOEev5EtC0
    access-key-secret: CcFTGjbDyIft0HgcaHbyAT7Lj9KIiN
    sign-name: 蜂鸟
rpc:
  btc:
    user: bitcoinrpc
    password: xxxx
    allowip: 192.168.0.123
    port: 8332
sharding:
  jdbc:
    datasource:
      accountdb:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://db-server:3306/h_pool_share?characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        username: root
        password: wg666666
      admindb:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://db-server:3306/h_pool_share_admin?characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
        username: root
        password: wg666666